import { Injectable, signal } from '@angular/core';

export type Lang = 'fr' | 'ar' | 'en';

export const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  fr: {
    // Navbar
    'nav.dashboard': 'Dashboard',
    'nav.exams': 'Examens',
    'nav.users': 'Utilisateurs',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.groups': 'Groupes',

    // Landing
    'landing.badge': '🎓 Plateforme d\'examens en ligne',
    'landing.title1': 'Créez, gérez et passez',
    'landing.title2': 'vos examens',
    'landing.title3': 'facilement',
    'landing.subtitle': 'ExamPlatform vous permet de créer des examens avec questions et réponses, de les partager avec vos étudiants et de suivre leurs performances en temps réel.',
    'landing.start': 'Commencer gratuitement →',
    'landing.signin': 'Se connecter',
    'landing.stat1': 'En ligne',
    'landing.stat2': 'Examens',
    'landing.stat3': 'Interactif',
    'landing.feat.title': 'Tout ce dont vous avez besoin',
    'landing.feat.label': 'Fonctionnalités',
    'landing.how.label': 'Comment ça marche',
    'landing.how.title': 'Simple en 3 étapes',
    'landing.step1.title': 'Créez votre compte',
    'landing.step1.desc': 'Inscrivez-vous gratuitement et accédez à votre tableau de bord personnalisé.',
    'landing.step2.title': 'Créez un examen',
    'landing.step2.desc': 'Ajoutez vos questions, définissez les bonnes réponses et activez l\'examen.',
    'landing.step3.title': 'Suivez les résultats',
    'landing.step3.desc': 'Les candidats passent le test et vous voyez les scores en temps réel.',
    'landing.cta.title': 'Prêt à commencer ?',
    'landing.cta.desc': 'Rejoignez ExamPlatform et créez votre premier examen en quelques minutes.',
    'landing.cta.btn': 'Créer un compte gratuit',
    'landing.cta.already': 'J\'ai déjà un compte',
    'landing.footer': '© 2026 ExamPlatform. Tous droits réservés.',

    // Login / Register
    'login.title': 'Connexion',
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.btn': 'Se connecter',
    'login.loading': 'Connexion...',
    'login.error': 'Email ou mot de passe incorrect.',
    'login.no_account': 'Pas encore de compte ?',
    'login.register': 'S\'inscrire',
    'register.title': 'Créer un compte',
    'register.name': 'Nom complet',
    'register.btn': 'Créer mon compte',
    'register.loading': 'Création...',
    'register.error': 'Erreur lors de la création du compte.',
    'register.have_account': 'Déjà un compte ?',

    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcome': 'Bienvenue,',
    'dashboard.new_exam': '+ Nouvel examen',
    'dashboard.activated': 'Examens activés',
    'dashboard.created': 'En cours de création',
    'dashboard.suspended': 'Suspendus',
    'dashboard.total': 'Total examens',
    'dashboard.recent': 'Mes examens récents',
    'dashboard.empty': 'Vous n\'avez pas encore créé d\'examen.',
    'dashboard.first': 'Créer mon premier examen',
    'dashboard.popular': 'Examens populaires',
    'dashboard.loading': 'Chargement...',
    'dashboard.see': 'Voir',
    'dashboard.edit': 'Modifier',
    'dashboard.questions': 'questions',
    'dashboard.share': 'Partager',
    'dashboard.cancel': 'Annuler',
    'dashboard.share_exam': 'Partager l\'examen',
    'dashboard.select_group': 'Sélectionner un groupe',
    'dashboard.choose_group': 'Choisir un groupe',
    'dashboard.no_admin_groups': 'Vous devez être admin d\'un groupe pour partager un examen',
    'dashboard.exam_shared': 'Examen partagé avec succès !',
    'dashboard.share_error': 'Erreur lors du partage',
    'dashboard.join_group': 'Rejoindre un groupe',
    'dashboard.request_join': 'Demander à rejoindre',
    'dashboard.join_request_sent': 'Demande envoyée à l\'admin',
    'dashboard.join_request_error': 'Erreur lors de la demande',
    'dashboard.no_groups_to_join': 'Aucun groupe disponible à rejoindre',
    'dashboard.my_exams': 'Mes examens',
    'dashboard.public_exams': 'Examens publics',
    'dashboard.shared_exams': 'Examens partagés',
    'dashboard.take_test': 'Passer le test',
    'dashboard.manage_groups': 'Gérer mes groupes',
    'dashboard.joined_success': 'Vous avez rejoint le groupe !',
    'dashboard.join_error': 'Erreur lors de l\'adhésion',
    'dashboard.request_sent': 'Demande envoyée',
    'dashboard.request_error': 'Erreur lors de l\'envoi de la demande',
    'dashboard.visibility_error': 'Erreur lors du changement de visibilité',
    'dashboard.search': 'Rechercher',
    'dashboard.search_group_placeholder': 'Rechercher par nom ou description...',
    'dashboard.search_hint': '🔍 Recherchez des groupes par nom ou description',
    'dashboard.no_groups_found': 'Aucun groupe trouvé.',
    'dashboard.join': 'Rejoindre',
    'dashboard.request_to_join': 'Demander à rejoindre',
    'dashboard.request_pending': 'Demande en attente',
    'dashboard.code_copied': 'Code copié !',

    // Exams
    'exams.title': 'Examens',
    'exams.found': 'examen(s) trouvé(s)',
    'exams.new': '+ Nouvel examen',
    'exams.search': 'Rechercher par code ou description...',
    'exams.all_status': 'Tous les statuts',
    'exams.loading': 'Chargement des examens...',
    'exams.empty': 'Aucun examen trouvé.',
    'exams.code': 'Code',
    'exams.desc': 'Description',
    'exams.questions': 'Questions',
    'exams.status': 'Statut',
    'exams.date': 'Date',
    'exams.actions': 'Actions',
    'exams.delete_confirm': 'Supprimer cet examen ?',

    'exams.visibility': 'Visibilité',
    'exams.view': 'Voir',
    'exams.delete': 'Supprimer',
    'exams.delete_confirm_text': 'Voulez-vous vraiment supprimer cet examen ? Cette action est irréversible.',
    'exams.delete_confirm_yes': 'Oui, supprimer',
    'exams.delete_confirm_no': 'Annuler',
    'exams.deleted_success': 'a été supprimé',
    'exams.delete_error': 'Erreur de suppression',
    'exams.delete_error_text': 'Impossible de supprimer cet examen.',
    'exams.cancel': 'Annuler',

    'exam.loading': 'Chargement de l\'examen...',
    'exam.take_test': 'Passer le test',
    'exam.edit': 'Modifier',
    'exam.back': 'Retour',
    'exam.questions_count': 'Questions',
    'exam.created_date': 'Créé le',
    'exam.best_score': 'Meilleur score',
    'exam.champion': 'Champion',
    'exam.questions_list': 'Questions de l\'examen',
    'exam.no_questions': 'Aucune question dans cet examen.',
    'exam.tests_history': 'Historique des tests',
    'exam.test_id': 'Test ID',
    'exam.candidate': 'Candidat',
    'exam.score': 'Score',


    // Statuts
    'status.CREATED': 'Créé',
    'status.ACTIVATED': 'Activé',
    'status.SUSPENDED': 'Suspendu',

    // Exam Form traductions
    'form.title': 'Nouvel examen',
    'form.edit_title': 'Modifier l\'examen',
    'form.subtitle': 'Créez votre examen avec questions et réponses',
    'form.general_info': 'Informations générales',
    'form.description_placeholder': 'Description de l\'examen',
    'form.questions_section': 'Questions',
    'form.question_content': 'Contenu de la question',
    'form.question_placeholder': 'Écrivez votre question ici...',
    'form.question_description': 'Description (optionnelle)',
    'form.question_desc_placeholder': 'Indice ou explication...',
    'form.answers_section': 'Réponses',
    'form.answer_placeholder': 'Contenu de la réponse',
    'form.correct_answer': 'Bonne réponse',
    'form.wrong_answer': 'Mauvaise réponse',
    'form.save_question': 'Enregistrer la question',
    'form.update_question': 'Mettre à jour la question',
    'form.remove_question': 'Supprimer la question',
    'form.remove_answer': 'Supprimer la réponse',
    'form.update': 'Mettre à jour l\'examen',
    'form.submit': 'Créer l\'examen',
    'form.loading': 'Chargement...',
    'form.saving': 'Enregistrement...',
    'form.saved': 'Enregistré !',
    'form.error_state': 'Erreur',
    'form.back': 'Retour',
    'form.cancel': 'Annuler',
    'form.description': 'Description',
    'form.status': 'Statut',
    'form.visibility': 'Visibilité',
    'form.public': 'Public',
    'form.private': 'Privé',
    'form.question': 'Question',
    'form.update_answer': 'Mettre à jour la réponse',
    'form.save_answer': 'Enregistrer la réponse',
    'form.update_answer_short': 'MAJ',
    'form.no_questions': 'Aucune question. Cliquez sur le bouton ci-dessous pour commencer.',
    'form.add_answer': 'Ajouter une réponse',
    'form.add_question': 'Ajouter une question',

    'form.attachment': 'Document ou vidéo support (optionnel)',
    'form.add_attachment': 'Joindre un fichier',
    'form.uploading': 'Téléversement...',
    'form.upload_error': 'Erreur lors du téléversement.',
    'form.remove_attachment': 'Retirer le fichier',

    'form.attachment_hint': 'PDF, Word, image, audio ou vidéo (max 50 Mo)',

    'form.has_duration': 'Limiter la durée du test',
    'form.duration_placeholder': 'Durée en minutes',
    'form.minutes': 'minutes',

    'test.half_time_warning': 'Moitié du temps écoulée',
    'test.end_warning': 'Attention, le temps est presque écoulé !',
    'test.remaining': 'restant(es)',
    'test.time_up_title': 'Temps écoulé',
    'test.time_up_text': 'Vos réponses ont été envoyées automatiquement.',


    // Math Editor
    'math_editor.show_symbols': 'Afficher les symboles',
    'math_editor.hide_symbols': 'Masquer les symboles',
    'math_editor.show_preview': 'Afficher l\'aperçu',
    'math_editor.hide_preview': 'Masquer l\'aperçu',
    'math_editor.add_description': 'Ajouter une description',
    'math_editor.hide_description': 'Masquer la description',


    // Users
    'users.title': 'Utilisateurs',
    'users.add': '+ Ajouter',
    'users.new_title': 'Nouvel utilisateur',
    'users.edit_title': 'Modifier l\'utilisateur',
    'users.name': 'Nom',
    'users.email': 'Email',
    'users.password': 'Mot de passe',
    'users.name_ph': 'Nom complet',
    'users.email_ph': 'email@exemple.com',
    'users.pass_ph': '••••••••',
    'users.cancel': 'Annuler',
    'users.create': 'Créer',
    'users.update': 'Mettre à jour',
    'users.loading': 'Chargement...',
    'users.delete_confirm': 'Supprimer cet utilisateur ?',

    // Groups
    'groups.title': 'Mes Groupes',
    'groups.subtitle': 'Gérez vos groupes et partagez des examens',
    'groups.create': 'Créer un groupe',
    'groups.create_new': 'Créer un nouveau groupe',
    'groups.name': 'Nom du groupe',
    'groups.description': 'Description',
    'groups.no_description': 'Aucune description',
    'groups.loading': 'Chargement des groupes...',
    'groups.empty': 'Vous n\'avez pas encore de groupe',
    'groups.create_first': 'Créer mon premier groupe',
    'groups.add_member': 'Ajouter un membre',
    'groups.add_exam': 'Ajouter un examen',
    'groups.members': 'Membres',
    'groups.admins': 'Administrateurs',
    'groups.delete_confirm': 'Supprimer ce groupe ?',
    'groups.remove_member_confirm': 'Retirer ce membre ?',
    'groups.cancel': 'Annuler',
    'groups.search_user': 'Rechercher un utilisateur',
    'groups.select_exam': 'Sélectionner un examen',
    'groups.choose_exam': 'Choisir un examen',
    'groups.share': 'Partager',
    'groups.add': 'Ajouter',
    'groups.join_requests': 'Demandes de rejoindre',
    'groups.no_requests': 'Aucune demande en attente',
    'groups.shared_exams': 'Examens partagés',
    'groups.view_exam': 'Voir l\'examen',
    'groups.remove_exam': 'Retirer du groupe',
    'groups.confirm_remove_exam': 'Retirer cet examen du groupe ?',
    'groups.error_remove_exam': 'Erreur lors du retrait de l\'examen',
    'groups.by': 'Par',
    'groups.creator': 'Créé par',
    'groups.accept': 'Accepter',
    'groups.reject': 'Refuser',
    'groups.admin_badge': 'Admin',
    'groups.more_members': 'autres',
    'groups.remove_member': 'Retirer le membre',
    'groups.delete_group': 'Supprimer le groupe',
    'groups.requests_title': 'Demandes d\'adhésion',
    'groups.name_placeholder': 'Nom du groupe',
    'groups.desc_placeholder': 'Description du groupe',
    'groups.search_placeholder': 'Rechercher par nom ou email...',
    'groups.unknown_creator': 'Créateur inconnu',
    'groups.no_group_selected': 'Aucun groupe sélectionné',


    'groups.confirm_remove_exam_title': 'Retirer l\'examen',
    'groups.confirm_remove_exam_text': 'Voulez-vous vraiment retirer cet examen du groupe ?',
    'groups.confirm_remove_exam_confirm': 'Oui, retirer',
    'groups.confirm_remove_exam_cancel': 'Annuler',
    'groups.exam_removed_success': 'Examen retiré avec succès !',
    'groups.exam_removed_error': 'Impossible de retirer l\'examen du groupe.',
    'groups.exam_removed_toast': 'Examen retiré',

    'groups.confirm_share_exam_title': 'Partager un examen',
    'groups.confirm_share_exam_text': 'Voulez-vous vraiment partager cet examen avec ce groupe ?',
    'groups.confirm_share_exam_confirm': 'Oui, partager',
    'groups.confirm_share_exam_cancel': 'Annuler',
    'groups.exam_shared_success': 'Examen partagé avec succès !',
    'groups.exam_shared_error': 'Impossible de partager l\'examen avec le groupe.',
    'groups.exam_shared_toast': 'Examen partagé',

    'groups.confirm_delete_group_title': 'Supprimer le groupe',
    'groups.confirm_delete_group_text': 'Voulez-vous vraiment supprimer ce groupe ? Cette action est irréversible.',
    'groups.confirm_delete_group_confirm': 'Oui, supprimer',
    'groups.confirm_delete_group_cancel': 'Annuler',
    'groups.group_deleted_success': 'Groupe supprimé avec succès !',
    'groups.group_deleted_error': 'Impossible de supprimer le groupe.',

    'groups.confirm_join_request_title': 'Demande d\'adhésion',
    'groups.confirm_join_request_text': 'Voulez-vous vraiment demander à rejoindre ce groupe ?',
    'groups.confirm_join_request_confirm': 'Oui, envoyer la demande',
    'groups.confirm_join_request_cancel': 'Annuler',
    'groups.join_request_sent': 'Demande envoyée avec succès !',
    'groups.join_request_pending': 'Demande déjà en attente',
    'groups.join_request_error': 'Erreur lors de l\'envoi de la demande',
    'groups.already_member': 'Vous êtes déjà membre de ce groupe',


    'groups.requests_disabled_title': 'Seuls les administrateurs peuvent voir les demandes',

    'groups.add_member_tooltip': 'Ajouter un membre au groupe',
    'groups.add_exam_tooltip': 'Partager un examen avec le groupe',
    'groups.add_member_disabled_tooltip': 'Seuls les administrateurs peuvent ajouter des membres',
    'groups.add_exam_disabled_tooltip': 'Seuls les administrateurs peuvent partager des examens',

    'groups.remove_exam_disabled_tooltip': 'Seuls les administrateurs peuvent retirer des examens',

    'groups.already_member_of_group': 'est déjà membre de ce groupe.',
    'groups.member_added': 'a rejoint le groupe',
    'groups.add_member_error': 'Impossible d\'ajouter le membre.',


    'groups.exam_already_shared': 'Examen déjà partagé',
    'groups.exam_already_shared_text': 'Cet examen est déjà partagé avec ce groupe :',




    // Correction
    'correction.loading': 'Chargement de la correction...',
    'correction.congrats': 'Félicitations ! Excellent résultat !',
    'correction.keep_trying': 'Continuez vos efforts !',
    'correction.summary': 'Résumé',
    'correction.correct': 'Bonnes réponses',
    'correction.incorrect': 'Mauvaises réponses',
    'correction.detailed': 'Correction détaillée',
    'correction.your_answer': 'Votre réponse',
    'correction.correct_answer': 'Réponse correcte',
    'correction.explanation': 'Explication',
    'correction.no_answer': 'Aucune réponse',
    'correction.back_to_dashboard': 'Retour au tableau de bord',
    'correction.detailed_title': '📝 Correction détaillée',
    'correction.question_label': 'Question',
    'correction.correct_badge': '✓ CORRECTE',
    'correction.incorrect_badge': '✗ INCORRECTE',
    'correction.your_answer_correct_text': '✓ Vous avez coché (bonne réponse)',
    'correction.your_answer_wrong_text': '✗ Vous avez coché (mauvaise réponse)',
    'correction.correct_not_selected_text': '💡 Bonne réponse non cochée',
    'correction.not_selected_text': '• Non coché',
    'correction.hint_text': '💡 La bonne réponse était :',

    'test.confirm_title': 'Commencer le test',
    'test.confirm_text': 'Êtes-vous prêt à passer l\'examen numéro',
    'test.confirm_confirm': '🎯 Commencer',
    'test.confirm_cancel': 'Annuler',


    // Page Test
    'test.created_by': 'Créé par',
    'test.questions_count': 'Questions',
    'test.progress': 'Progression',
    'test.question': 'Question',
    'test.answers_selected': 'réponse(s) sélectionnée(s)',
    'test.warning': 'Vous avez répondu à',
    'test.on': 'sur',
    'test.submit': 'Soumettre le test',
    'test.submitting': 'Soumission en cours...',
    'test.loading': 'Chargement du test...',

    'test.incomplete_title': 'Test incomplet',
    'test.incomplete_text': 'Veuillez répondre à toutes les questions avant de soumettre.',
    'test.continue': 'Continuer',
    'test.confirm_submit_title': 'Soumettre le test',
    'test.confirm_submit_text': 'Voulez-vous vraiment soumettre vos réponses pour',
    'test.confirm_submit_confirm': 'Oui, soumettre',
    'test.confirm_submit_cancel': 'Non, vérifier encore',
    'test.success': 'Test soumis !',
    'test.success_message': 'Vos réponses ont été enregistrées avec succès.',
    'test.error': 'Erreur',
    'test.error_message': 'Une erreur est survenue lors de la soumission.',
    'test.close': 'Fermer',

    //test-result
    'test_result.loading': 'Chargement des résultats...',
    'test_result.back_to_dashboard': 'Retour au tableau de bord',
    'test_result.congrats': '🎉 Félicitations !',
    'test_result.keep_trying': '📚 Continuez vos efforts !',
    'test_result.summary': 'Résumé du test',
    'test_result.candidate_name': 'Nom du candidat',
    'test_result.exam_creator': 'Créateur de l\'examen',
    'test_result.correct_answers': 'Bonnes réponses',
    'test_result.wrong_answers': 'Mauvaises réponses',
    'test_result.score': 'Note obtenue',
    'test_result.date': 'Date du test',
    'test_result.view_correction': 'Voir la correction détaillée',

    'exams.tests': 'Tests',
    'exams.tests_list': 'Tests passés',
    'exams.candidate': 'Candidat',
    'exams.score': 'Score',
    'exams.percentage': 'Pourcentage',
    'exams.no_tests': 'Aucun test',
    'exams.no_tests_text': 'Cet examen n\'a pas encore été passé.',
    'exams.close': 'Fermer',


    'exams.access_denied': 'Accès refusé',
    'exams.no_rights': 'Vous n\'avez pas le droit de consulter les résultats de cet examen.',

    'test_result.retake_test': ' Refaire le test',
    'test_result.retake_confirm_title': 'Nouvelle tentative',
    'test_result.retake_confirm_text': 'Voulez-vous vraiment refaire ce test ?',
    'test_result.retake_confirm_yes': 'Oui, recommencer',
    'test_result.retake_confirm_no': 'Non, annuler',

    ///
    'test.limit_reached_title': 'Limite atteinte',
    'test.limit_reached_text': 'Vous avez déjà utilisé vos 3 tentatives pour cet examen.',
    'test.limit_reached': 'Nombre maximum de tentatives atteint.',

    'exams.test_details': 'Détails du test',
    'exams.correct_answers': 'Bonnes réponses',
    'exams.wrong_answers': 'Mauvaises réponses',
    'exams.test_id': 'ID du test',

    'exams.view_details': 'Voir les détails',

    'test.previous': 'Précédent',
    'test.next': 'Suivant',
    'form.previous_question': 'Précédente',
    'form.next_question': 'Suivante',

    'form.generate_ai': "Générer avec l'IA",
    'form.ai_subject': "Sujet",
    'form.ai_subject_placeholder': "ex: Les dérivées et primitives",
    'form.ai_subject_required': "Le sujet est requis.",
    'form.ai_level': "Niveau (optionnel)",
    'form.ai_level_placeholder': "ex: Terminale S, Licence 1",
    'form.ai_count': "Nombre de questions",
    'form.ai_language': "Langue",
    'form.ai_multiple_correct': "Autoriser plusieurs bonnes réponses par question",
    'form.ai_generate_button': "Générer",
    'form.ai_generating': "Génération en cours...",
    'form.ai_error': "Erreur lors de la génération IA.",

    'form.ai_difficulty': "Niveau de difficulté",
    'form.ai_difficulty_easy': "Facile",
    'form.ai_difficulty_medium': "Moyen",
    'form.ai_difficulty_advanced': "Avancé",
    'form.ai_reference_file': "Document de référence (optionnel)",
    'form.ai_add_reference_file': "Ajouter un document",
    'form.ai_reference_file_hint': "PDF, Word (.docx) ou texte (.txt) — 10 Mo max",
    'form.ai_file_too_large': "Le fichier dépasse 10 Mo.",

    // Result
    'result.view_correction': 'Voir le corrigé',
    'result.back_to_dashboard': 'Retour au tableau de bord',

    'groups.make_public': 'Rendre ce groupe public',
    'groups.public_hint': 'Les groupes publics sont visibles par tous et rejoignables directement.',
    'groups.visibility_error': 'Erreur lors du changement de visibilité',

      //Admin
    'admin.title': "Administration",
    'admin.subtitle': "Gestion de la plateforme",
    'admin.tab_stats': "Statistiques",
    'admin.tab_users': "Utilisateurs",
    'admin.tab_exams': "Examens",
    'admin.tab_groups': "Groupes",
    'admin.loading': "Chargement...",
    'admin.stat_users': "Utilisateurs",
    'admin.stat_exams': "Examens",
    'admin.stat_questions': "Questions",
    'admin.stat_groups': "Groupes",
    'admin.stat_tests': "Tests passés",
    'admin.search_user': "Rechercher un utilisateur...",
    'admin.search_exam': "Rechercher un examen...",
    'admin.search_group': "Rechercher un groupe...",
    'admin.col_name': "Nom",
    'admin.col_email': "Email",
    'admin.col_code': "Code",
    'admin.col_description': "Description",
    'admin.col_visibility': "Visibilité",
    'admin.col_actions': "Actions",
    'admin.col_group_name': "Nom du groupe",
    'admin.col_creator': "Créateur",
    'admin.col_members': "Membres",
    'admin.promote': "Promouvoir",
    'admin.demote': "Rétrograder",
    'admin.delete_user': "Supprimer l'utilisateur",
    'admin.delete_exam': "Supprimer l'examen",
    'admin.delete_group': "Supprimer le groupe",
    'admin.confirm_promote': "Promouvoir cet utilisateur en admin ?",
    'admin.confirm_demote': "Retirer les droits admin ?",
    'admin.confirm_delete_user': "Supprimer cet utilisateur ?",
    'admin.confirm_delete_exam': "Supprimer cet examen ?",
    'admin.confirm_delete_group': "Supprimer ce groupe ?",
    'admin.confirm_yes': "Oui",
    'admin.confirm_no': "Annuler",
    'admin.promoted_success': "Utilisateur promu admin",
    'admin.demoted_success': "Droits admin retirés",
    'admin.deleted_user_success': "Utilisateur supprimé",
    'admin.deleted_exam_success': "Examen supprimé",
    'admin.deleted_group_success': "Groupe supprimé",
    'admin.action_error': "Une erreur est survenue.",
    'admin.cannot_delete_self': "Tu ne peux pas supprimer ton propre compte ici.",
    'nav.admin': "Admin",

  },

  en: {
    // Navbar
    'nav.dashboard': 'Dashboard',
    'nav.exams': 'Exams',
    'nav.users': 'Users',
    'nav.login': 'Sign in',
    'nav.logout': 'Sign out',
    'nav.groups': 'Groups',

    // Landing
    'landing.badge': '🎓 Online exam platform',
    'landing.title1': 'Create, manage and take',
    'landing.title2': 'your exams',
    'landing.title3': 'easily',
    'landing.subtitle': 'Amtihan lets you create exams with questions and answers, share them with your students, and track their performance in real time.',
    'landing.start': 'Start for free →',
    'landing.signin': 'Sign in',
    'landing.stat1': 'Online',
    'landing.stat2': 'Exams',
    'landing.stat3': 'Interactive',
    'landing.feat.title': 'Everything you need',
    'landing.feat.label': 'Features',
    'landing.how.label': 'How it works',
    'landing.how.title': 'Simple in 3 steps',
    'landing.step1.title': 'Create your account',
    'landing.step1.desc': 'Sign up for free and access your personalized dashboard.',
    'landing.step2.title': 'Create an exam',
    'landing.step2.desc': 'Add your questions, define the correct answers, and activate the exam.',
    'landing.step3.title': 'Track the results',
    'landing.step3.desc': 'Candidates take the test and you see their scores in real time.',
    'landing.cta.title': 'Ready to get started?',
    'landing.cta.desc': 'Join Amtihan and create your first exam in a few minutes.',
    'landing.cta.btn': 'Create a free account',
    'landing.cta.already': 'I already have an account',
    'landing.footer': '© 2026 Amtihan. All rights reserved.',

    // Login / Register
    'login.title': 'Sign in',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.btn': 'Sign in',
    'login.loading': 'Signing in...',
    'login.error': 'Incorrect email or password.',
    'login.no_account': 'Don\'t have an account yet?',
    'login.register': 'Sign up',
    'register.title': 'Create an account',
    'register.name': 'Full name',
    'register.btn': 'Create my account',
    'register.loading': 'Creating...',
    'register.error': 'An error occurred while creating the account.',
    'register.have_account': 'Already have an account?',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome,',
    'dashboard.new_exam': '+ New exam',
    'dashboard.activated': 'Activated exams',
    'dashboard.created': 'In progress',
    'dashboard.suspended': 'Suspended',
    'dashboard.total': 'Total exams',
    'dashboard.recent': 'My recent exams',
    'dashboard.empty': 'You haven\'t created any exam yet.',
    'dashboard.first': 'Create my first exam',
    'dashboard.popular': 'Popular exams',
    'dashboard.loading': 'Loading...',
    'dashboard.see': 'View',
    'dashboard.edit': 'Edit',
    'dashboard.questions': 'questions',
    'dashboard.share': 'Share',
    'dashboard.cancel': 'Cancel',
    'dashboard.share_exam': 'Share the exam',
    'dashboard.select_group': 'Select a group',
    'dashboard.choose_group': 'Choose a group',
    'dashboard.no_admin_groups': 'You must be an admin of a group to share an exam',
    'dashboard.exam_shared': 'Exam shared successfully!',
    'dashboard.share_error': 'Error while sharing',
    'dashboard.join_group': 'Join a group',
    'dashboard.request_join': 'Request to join',
    'dashboard.join_request_sent': 'Request sent to the admin',
    'dashboard.join_request_error': 'Error while sending the request',
    'dashboard.no_groups_to_join': 'No groups available to join',
    'dashboard.my_exams': 'My exams',
    'dashboard.public_exams': 'Public exams',
    'dashboard.shared_exams': 'Shared exams',
    'dashboard.take_test': 'Take the test',
    'dashboard.manage_groups': 'Manage my groups',
    'dashboard.joined_success': 'You have joined the group!',
    'dashboard.join_error': 'Error while joining',
    'dashboard.request_sent': 'Request sent',
    'dashboard.request_error': 'Error while sending the request',
    'dashboard.visibility_error': 'Error while changing visibility',
    'dashboard.search': 'Search',
    'dashboard.search_group_placeholder': 'Search by name or description...',
    'dashboard.search_hint': '🔍 Search for groups by name or description',
    'dashboard.no_groups_found': 'No group found.',
    'dashboard.join': 'Join',
    'dashboard.request_to_join': 'Request to join',
    'dashboard.request_pending': 'Request pending',
    'dashboard.code_copied': 'Code copied!',

    // Exams
    'exams.title': 'Exams',
    'exams.found': 'exam(s) found',
    'exams.new': '+ New exam',
    'exams.search': 'Search by code or description...',
    'exams.all_status': 'All statuses',
    'exams.loading': 'Loading exams...',
    'exams.empty': 'No exam found.',
    'exams.code': 'Code',
    'exams.desc': 'Description',
    'exams.questions': 'Questions',
    'exams.status': 'Status',
    'exams.date': 'Date',
    'exams.actions': 'Actions',
    'exams.delete_confirm': 'Delete this exam?',

    'exams.visibility': 'Visibility',
    'exams.view': 'View',
    'exams.delete': 'Delete',
    'exams.delete_confirm_text': 'Do you really want to delete this exam? This action cannot be undone.',
    'exams.delete_confirm_yes': 'Yes, delete',
    'exams.delete_confirm_no': 'Cancel',
    'exams.deleted_success': 'was deleted',
    'exams.delete_error': 'Deletion error',
    'exams.delete_error_text': 'Unable to delete this exam.',
    'exams.cancel': 'Cancel',

    'exam.loading': 'Loading exam...',
    'exam.take_test': 'Take the test',
    'exam.edit': 'Edit',
    'exam.back': 'Back',
    'exam.questions_count': 'Questions',
    'exam.created_date': 'Created on',
    'exam.best_score': 'Best score',
    'exam.champion': 'Champion',
    'exam.questions_list': 'Exam questions',
    'exam.no_questions': 'No questions in this exam.',
    'exam.tests_history': 'Test history',
    'exam.test_id': 'Test ID',
    'exam.candidate': 'Candidate',
    'exam.score': 'Score',

    // Statuses
    'status.CREATED': 'Created',
    'status.ACTIVATED': 'Activated',
    'status.SUSPENDED': 'Suspended',

    // Exam Form translations
    'form.title': 'New exam',
    'form.edit_title': 'Edit exam',
    'form.subtitle': 'Create your exam with questions and answers',
    'form.general_info': 'General information',
    'form.description_placeholder': 'Exam description',
    'form.questions_section': 'Questions',
    'form.question_content': 'Question content',
    'form.question_placeholder': 'Write your question here...',
    'form.question_description': 'Description (optional)',
    'form.question_desc_placeholder': 'Hint or explanation...',
    'form.answers_section': 'Answers',
    'form.answer_placeholder': 'Answer content',
    'form.correct_answer': 'Correct answer',
    'form.wrong_answer': 'Wrong answer',
    'form.save_question': 'Save question',
    'form.update_question': 'Update question',
    'form.remove_question': 'Remove question',
    'form.remove_answer': 'Remove answer',
    'form.update': 'Update exam',
    'form.submit': 'Create exam',
    'form.loading': 'Loading...',
    'form.saving': 'Saving...',
    'form.saved': 'Saved!',
    'form.error_state': 'Error',
    'form.back': 'Back',
    'form.cancel': 'Cancel',
    'form.description': 'Description',
    'form.status': 'Status',
    'form.visibility': 'Visibility',
    'form.public': 'Public',
    'form.private': 'Private',
    'form.question': 'Question',
    'form.update_answer': 'Update answer',
    'form.save_answer': 'Save answer',
    'form.update_answer_short': 'Update',
    'form.no_questions': 'No questions yet. Click the button below to start.',
    'form.add_answer': 'Add an answer',
    'form.add_question': 'Add a question',

    'form.attachment': 'Supporting document or video (optional)',
    'form.add_attachment': 'Attach a file',
    'form.uploading': 'Uploading...',
    'form.upload_error': 'Error while uploading.',
    'form.remove_attachment': 'Remove file',

    'form.attachment_hint': 'PDF, Word, image, audio or video (max 50 MB)',

    'form.has_duration': 'Limit the test duration',
    'form.duration_placeholder': 'Duration in minutes',
    'form.minutes': 'minutes',

    'test.half_time_warning': 'Half the time has elapsed',
    'test.end_warning': 'Warning, time is almost up!',
    'test.remaining': 'remaining',
    'test.time_up_title': 'Time\'s up',
    'test.time_up_text': 'Your answers were submitted automatically.',

    // Math Editor
    'math_editor.show_symbols': 'Show symbols',
    'math_editor.hide_symbols': 'Hide symbols',
    'math_editor.show_preview': 'Show preview',
    'math_editor.hide_preview': 'Hide preview',
    'math_editor.add_description': 'Add a description',
    'math_editor.hide_description': 'Hide description',

    // Users
    'users.title': 'Users',
    'users.add': '+ Add',
    'users.new_title': 'New user',
    'users.edit_title': 'Edit user',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.password': 'Password',
    'users.name_ph': 'Full name',
    'users.email_ph': 'email@example.com',
    'users.pass_ph': '••••••••',
    'users.cancel': 'Cancel',
    'users.create': 'Create',
    'users.update': 'Update',
    'users.loading': 'Loading...',
    'users.delete_confirm': 'Delete this user?',

    // Groups
    'groups.title': 'My Groups',
    'groups.subtitle': 'Manage your groups and share exams',
    'groups.create': 'Create a group',
    'groups.create_new': 'Create a new group',
    'groups.name': 'Group name',
    'groups.description': 'Description',
    'groups.no_description': 'No description',
    'groups.loading': 'Loading groups...',
    'groups.empty': 'You don\'t have any group yet',
    'groups.create_first': 'Create my first group',
    'groups.add_member': 'Add a member',
    'groups.add_exam': 'Add an exam',
    'groups.members': 'Members',
    'groups.admins': 'Admins',
    'groups.delete_confirm': 'Delete this group?',
    'groups.remove_member_confirm': 'Remove this member?',
    'groups.cancel': 'Cancel',
    'groups.search_user': 'Search for a user',
    'groups.select_exam': 'Select an exam',
    'groups.choose_exam': 'Choose an exam',
    'groups.share': 'Share',
    'groups.add': 'Add',
    'groups.join_requests': 'Join requests',
    'groups.no_requests': 'No pending requests',
    'groups.shared_exams': 'Shared exams',
    'groups.view_exam': 'View exam',
    'groups.remove_exam': 'Remove from group',
    'groups.confirm_remove_exam': 'Remove this exam from the group?',
    'groups.error_remove_exam': 'Error while removing the exam',
    'groups.by': 'By',
    'groups.creator': 'Created by',
    'groups.accept': 'Accept',
    'groups.reject': 'Reject',
    'groups.admin_badge': 'Admin',
    'groups.more_members': 'more',
    'groups.remove_member': 'Remove member',
    'groups.delete_group': 'Delete group',
    'groups.requests_title': 'Join requests',
    'groups.name_placeholder': 'Group name',
    'groups.desc_placeholder': 'Group description',
    'groups.search_placeholder': 'Search by name or email...',
    'groups.unknown_creator': 'Unknown creator',
    'groups.no_group_selected': 'No group selected',

    'groups.confirm_remove_exam_title': 'Remove exam',
    'groups.confirm_remove_exam_text': 'Do you really want to remove this exam from the group?',
    'groups.confirm_remove_exam_confirm': 'Yes, remove',
    'groups.confirm_remove_exam_cancel': 'Cancel',
    'groups.exam_removed_success': 'Exam removed successfully!',
    'groups.exam_removed_error': 'Unable to remove the exam from the group.',
    'groups.exam_removed_toast': 'Exam removed',

    'groups.confirm_share_exam_title': 'Share an exam',
    'groups.confirm_share_exam_text': 'Do you really want to share this exam with this group?',
    'groups.confirm_share_exam_confirm': 'Yes, share',
    'groups.confirm_share_exam_cancel': 'Cancel',
    'groups.exam_shared_success': 'Exam shared successfully!',
    'groups.exam_shared_error': 'Unable to share the exam with the group.',
    'groups.exam_shared_toast': 'Exam shared',

    'groups.confirm_delete_group_title': 'Delete group',
    'groups.confirm_delete_group_text': 'Do you really want to delete this group? This action cannot be undone.',
    'groups.confirm_delete_group_confirm': 'Yes, delete',
    'groups.confirm_delete_group_cancel': 'Cancel',
    'groups.group_deleted_success': 'Group deleted successfully!',
    'groups.group_deleted_error': 'Unable to delete the group.',

    'groups.confirm_join_request_title': 'Join request',
    'groups.confirm_join_request_text': 'Do you really want to request to join this group?',
    'groups.confirm_join_request_confirm': 'Yes, send the request',
    'groups.confirm_join_request_cancel': 'Cancel',
    'groups.join_request_sent': 'Request sent successfully!',
    'groups.join_request_pending': 'Request already pending',
    'groups.join_request_error': 'Error while sending the request',
    'groups.already_member': 'You are already a member of this group',

    'groups.requests_disabled_title': 'Only admins can view requests',

    'groups.add_member_tooltip': 'Add a member to the group',
    'groups.add_exam_tooltip': 'Share an exam with the group',
    'groups.add_member_disabled_tooltip': 'Only admins can add members',
    'groups.add_exam_disabled_tooltip': 'Only admins can share exams',

    'groups.remove_exam_disabled_tooltip': 'Only admins can remove exams',

    'groups.already_member_of_group': 'is already a member of this group.',
    'groups.member_added': 'joined the group',
    'groups.add_member_error': 'Unable to add the member.',

    'groups.exam_already_shared': 'Exam already shared',
    'groups.exam_already_shared_text': 'This exam is already shared with this group:',

    // Correction
    'correction.loading': 'Loading correction...',
    'correction.congrats': 'Congratulations! Excellent result!',
    'correction.keep_trying': 'Keep up the effort!',
    'correction.summary': 'Summary',
    'correction.correct': 'Correct answers',
    'correction.incorrect': 'Wrong answers',
    'correction.detailed': 'Detailed correction',
    'correction.your_answer': 'Your answer',
    'correction.correct_answer': 'Correct answer',
    'correction.explanation': 'Explanation',
    'correction.no_answer': 'No answer',
    'correction.back_to_dashboard': 'Back to dashboard',
    'correction.detailed_title': '📝 Detailed correction',
    'correction.question_label': 'Question',
    'correction.correct_badge': '✓ CORRECT',
    'correction.incorrect_badge': '✗ INCORRECT',
    'correction.your_answer_correct_text': '✓ You selected (correct answer)',
    'correction.your_answer_wrong_text': '✗ You selected (wrong answer)',
    'correction.correct_not_selected_text': '💡 Correct answer not selected',
    'correction.not_selected_text': '• Not selected',
    'correction.hint_text': '💡 The correct answer was:',

    'test.confirm_title': 'Start the test',
    'test.confirm_text': 'Are you ready to take exam number',
    'test.confirm_confirm': '🎯 Start',
    'test.confirm_cancel': 'Cancel',

    // Test Page
    'test.created_by': 'Created by',
    'test.questions_count': 'Questions',
    'test.progress': 'Progress',
    'test.question': 'Question',
    'test.answers_selected': 'answer(s) selected',
    'test.warning': 'You have answered',
    'test.on': 'out of',
    'test.submit': 'Submit the test',
    'test.submitting': 'Submitting...',
    'test.loading': 'Loading test...',

    'test.incomplete_title': 'Incomplete test',
    'test.incomplete_text': 'Please answer all questions before submitting.',
    'test.continue': 'Continue',
    'test.confirm_submit_title': 'Submit the test',
    'test.confirm_submit_text': 'Do you really want to submit your answers for',
    'test.confirm_submit_confirm': 'Yes, submit',
    'test.confirm_submit_cancel': 'No, check again',
    'test.success': 'Test submitted!',
    'test.success_message': 'Your answers have been saved successfully.',
    'test.error': 'Error',
    'test.error_message': 'An error occurred during submission.',
    'test.close': 'Close',

    // test-result
    'test_result.loading': 'Loading results...',
    'test_result.back_to_dashboard': 'Back to dashboard',
    'test_result.congrats': '🎉 Congratulations!',
    'test_result.keep_trying': '📚 Keep up the effort!',
    'test_result.summary': 'Test summary',
    'test_result.candidate_name': 'Candidate name',
    'test_result.exam_creator': 'Exam creator',
    'test_result.correct_answers': 'Correct answers',
    'test_result.wrong_answers': 'Wrong answers',
    'test_result.score': 'Score obtained',
    'test_result.date': 'Test date',
    'test_result.view_correction': 'View detailed correction',

    'exams.tests': 'Tests',
    'exams.tests_list': 'Tests taken',
    'exams.candidate': 'Candidate',
    'exams.score': 'Score',
    'exams.percentage': 'Percentage',
    'exams.no_tests': 'No tests',
    'exams.no_tests_text': 'This exam has not been taken yet.',
    'exams.close': 'Close',

    'exams.access_denied': 'Access denied',
    'exams.no_rights': 'You do not have the right to view the results of this exam.',

    'test_result.retake_test': ' Retake the test',
    'test_result.retake_confirm_title': 'New attempt',
    'test_result.retake_confirm_text': 'Do you really want to retake this test?',
    'test_result.retake_confirm_yes': 'Yes, restart',
    'test_result.retake_confirm_no': 'No, cancel',

    ///
    'test.limit_reached_title': 'Limit reached',
    'test.limit_reached_text': 'You have already used your 3 attempts for this exam.',
    'test.limit_reached': 'Maximum number of attempts reached.',

    'exams.test_details': 'Test details',
    'exams.correct_answers': 'Correct answers',
    'exams.wrong_answers': 'Wrong answers',
    'exams.test_id': 'Test ID',

    'exams.view_details': 'View details',

    'test.previous': 'Previous',
    'test.next': 'Next',
    'form.previous_question': 'Previous',
    'form.next_question': 'Next',

    'form.generate_ai': "Generate with AI",
    'form.ai_subject': "Subject",
    'form.ai_subject_placeholder': "e.g. Derivatives and antiderivatives",
    'form.ai_subject_required': "The subject is required.",
    'form.ai_level': "Level (optional)",
    'form.ai_level_placeholder': "e.g. High school senior, 1st year college",
    'form.ai_count': "Number of questions",
    'form.ai_language': "Language",
    'form.ai_multiple_correct': "Allow multiple correct answers per question",
    'form.ai_generate_button': "Generate",
    'form.ai_generating': "Generating...",
    'form.ai_error': "Error during AI generation.",

    'form.ai_difficulty': "Difficulty level",
    'form.ai_difficulty_easy': "Easy",
    'form.ai_difficulty_medium': "Medium",
    'form.ai_difficulty_advanced': "Advanced",
    'form.ai_reference_file': "Reference document (optional)",
    'form.ai_add_reference_file': "Add a document",
    'form.ai_reference_file_hint': "PDF, Word (.docx) or text (.txt) — 10 MB max",
    'form.ai_file_too_large': "The file exceeds 10 MB.",

    // Result
    'result.view_correction': 'View correction',
    'result.back_to_dashboard': 'Back to dashboard',

    'groups.make_public': 'Make this group public',
    'groups.public_hint': 'Public groups are visible to everyone and can be joined directly.',
    'groups.visibility_error': 'Error while changing visibility',

    //Admin
    'admin.title': "Administration",
    'admin.subtitle': "Platform management",
    'admin.tab_stats': "Statistics",
    'admin.tab_users': "Users",
    'admin.tab_exams': "Exams",
    'admin.tab_groups': "Groups",
    'admin.loading': "Loading...",
    'admin.stat_users': "Users",
    'admin.stat_exams': "Exams",
    'admin.stat_questions': "Questions",
    'admin.stat_groups': "Groups",
    'admin.stat_tests': "Tests taken",
    'admin.search_user': "Search a user...",
    'admin.search_exam': "Search an exam...",
    'admin.search_group': "Search a group...",
    'admin.col_name': "Name",
    'admin.col_email': "Email",
    'admin.col_code': "Code",
    'admin.col_description': "Description",
    'admin.col_visibility': "Visibility",
    'admin.col_actions': "Actions",
    'admin.col_group_name': "Group name",
    'admin.col_creator': "Creator",
    'admin.col_members': "Members",
    'admin.promote': "Promote",
    'admin.demote': "Demote",
    'admin.delete_user': "Delete user",
    'admin.delete_exam': "Delete exam",
    'admin.delete_group': "Delete group",
    'admin.confirm_promote': "Promote this user to admin?",
    'admin.confirm_demote': "Remove admin rights?",
    'admin.confirm_delete_user': "Delete this user?",
    'admin.confirm_delete_exam': "Delete this exam?",
    'admin.confirm_delete_group': "Delete this group?",
    'admin.confirm_yes': "Yes",
    'admin.confirm_no': "Cancel",
    'admin.promoted_success': "User promoted to admin",
    'admin.demoted_success': "Admin rights removed",
    'admin.deleted_user_success': "User deleted",
    'admin.deleted_exam_success': "Exam deleted",
    'admin.deleted_group_success': "Group deleted",
    'admin.action_error': "An error occurred.",
    'admin.cannot_delete_self': "You cannot delete your own account here.",
    'nav.admin': "Admin",
  },

  ar: {
    // Navbar
    'nav.dashboard': 'لوحة التحكم',
    'nav.exams': 'الامتحانات',
    'nav.users': 'المستخدمون',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.groups': 'المجموعات',

    // Landing
    'landing.badge': '🎓 منصة الامتحانات الإلكترونية',
    'landing.title1': 'أنشئ وأدر واجتز',
    'landing.title2': 'امتحاناتك',
    'landing.title3': 'بكل سهولة',
    'landing.subtitle': 'تتيح لك ExamPlatform إنشاء امتحانات بأسئلة وأجوبة ومشاركتها مع طلابك ومتابعة أدائهم في الوقت الفعلي.',
    'landing.start': 'ابدأ مجاناً ←',
    'landing.signin': 'تسجيل الدخول',
    'landing.stat1': 'عبر الإنترنت',
    'landing.stat2': 'امتحانات',
    'landing.stat3': 'تفاعلي',
    'landing.feat.title': 'كل ما تحتاجه',
    'landing.feat.label': 'المميزات',
    'landing.how.label': 'كيف يعمل',
    'landing.how.title': 'بسيط في 3 خطوات',
    'landing.step1.title': 'أنشئ حسابك',
    'landing.step1.desc': 'سجّل مجاناً وادخل إلى لوحة التحكم الخاصة بك.',
    'landing.step2.title': 'أنشئ امتحاناً',
    'landing.step2.desc': 'أضف أسئلتك وحدد الإجابات الصحيحة وفعّل الامتحان.',
    'landing.step3.title': 'تابع النتائج',
    'landing.step3.desc': 'يؤدي المرشحون الاختبار وترى النتائج في الوقت الفعلي.',
    'landing.cta.title': 'هل أنت مستعد للبدء؟',
    'landing.cta.desc': 'انضم إلى ExamPlatform وأنشئ امتحانك الأول في دقائق.',
    'landing.cta.btn': 'إنشاء حساب مجاني',
    'landing.cta.already': 'لدي حساب بالفعل',
    'landing.footer': '© 2026 ExamPlatform. جميع الحقوق محفوظة.',

    // Login / Register
    'login.title': 'تسجيل الدخول',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.btn': 'تسجيل الدخول',
    'login.loading': 'جارٍ الدخول...',
    'login.error': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    'login.no_account': 'ليس لديك حساب؟',
    'login.register': 'إنشاء حساب',
    'register.title': 'إنشاء حساب',
    'register.name': 'الاسم الكامل',
    'register.btn': 'إنشاء حسابي',
    'register.loading': 'جارٍ الإنشاء...',
    'register.error': 'حدث خطأ أثناء إنشاء الحساب.',
    'register.have_account': 'لديك حساب بالفعل؟',

    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً،',
    'dashboard.new_exam': '+ امتحان جديد',
    'dashboard.activated': 'الامتحانات المفعّلة',
    'dashboard.created': 'قيد الإنشاء',
    'dashboard.suspended': 'موقوفة',
    'dashboard.total': 'إجمالي الامتحانات',
    'dashboard.recent': 'امتحاناتي الأخيرة',
    'dashboard.empty': 'لم تقم بإنشاء أي امتحان بعد.',
    'dashboard.first': 'إنشاء امتحاني الأول',
    'dashboard.popular': 'الامتحانات الشائعة',
    'dashboard.loading': 'جارٍ التحميل...',
    'dashboard.see': 'عرض',
    'dashboard.edit': 'تعديل',
    'dashboard.questions': 'أسئلة',
    'dashboard.share': 'مشاركة',
    'dashboard.cancel': 'إلغاء',
    'dashboard.share_exam': 'مشاركة الامتحان',
    'dashboard.select_group': 'اختيار مجموعة',
    'dashboard.choose_group': 'اختر مجموعة',
    'dashboard.no_admin_groups': 'يجب أن تكون مشرفاً على مجموعة لمشاركة الامتحان',
    'dashboard.exam_shared': 'تمت مشاركة الامتحان بنجاح!',
    'dashboard.share_error': 'خطأ أثناء المشاركة',
    'dashboard.join_group': 'انضمام إلى مجموعة',
    'dashboard.request_join': 'طلب الانضمام',
    'dashboard.join_request_sent': 'تم إرسال الطلب إلى المشرف',
    'dashboard.join_request_error': 'خطأ أثناء إرسال الطلب',
    'dashboard.no_groups_to_join': 'لا توجد مجموعات متاحة للانضمام',
    'dashboard.my_exams': 'امتحاناتي',
    'dashboard.public_exams': 'الامتحانات العامة',
    'dashboard.shared_exams': 'الامتحانات المشتركة',
    'dashboard.take_test': 'إجراء الاختبار',
    'dashboard.manage_groups': 'إدارة مجموعاتي',
    'dashboard.joined_success': 'لقد انضممت إلى المجموعة!',
    'dashboard.join_error': 'خطأ في الانضمام',
    'dashboard.request_sent': 'تم إرسال الطلب',
    'dashboard.request_error': 'خطأ في إرسال الطلب',
    'dashboard.visibility_error': 'خطأ في تغيير الرؤية',
    'dashboard.search': 'بحث',
    'dashboard.search_group_placeholder': 'البحث بالاسم أو الوصف...',
    'dashboard.search_hint': '🔍 ابحث عن مجموعات بالاسم أو الوصف',
    'dashboard.no_groups_found': 'لم يتم العثور على أي مجموعة.',
    'dashboard.join': 'انضم',
    'dashboard.request_to_join': 'طلب الانضمام',
    'dashboard.request_pending': 'طلب معلق',
    'dashboard.code_copied': 'تم نسخ الرمز!',

    // Exams
    'exams.title': 'الامتحانات',
    'exams.found': 'امتحان(ات) موجودة',
    'exams.new': '+ امتحان جديد',
    'exams.search': 'البحث بالكود أو الوصف...',
    'exams.all_status': 'جميع الحالات',
    'exams.loading': 'جارٍ تحميل الامتحانات...',
    'exams.empty': 'لم يتم العثور على أي امتحان.',
    'exams.code': 'الكود',
    'exams.desc': 'الوصف',
    'exams.questions': 'الأسئلة',
    'exams.status': 'الحالة',
    'exams.date': 'التاريخ',
    'exams.actions': 'الإجراءات',
    'exams.delete_confirm': 'حذف هذا الامتحان؟',

    'exams.visibility': 'الرؤية',
    'exams.view': 'عرض',
    'exams.delete': 'حذف',
    'exams.delete_confirm_text': 'هل تريد بالتأكيد حذف هذا الامتحان؟ هذا الإجراء لا رجعة فيه.',
    'exams.delete_confirm_yes': 'نعم، حذف',
    'exams.delete_confirm_no': 'إلغاء',
    'exams.deleted_success': 'تم حذفه',
    'exams.delete_error': 'خطأ في الحذف',
    'exams.delete_error_text': 'لا يمكن حذف هذا الامتحان.',
    'exams.cancel': 'إلغاء',

    'exam.loading': 'جاري تحميل الامتحان...',
    'exam.take_test': 'إجراء الاختبار',
    'exam.edit': 'تعديل',
    'exam.back': 'رجوع',
    'exam.questions_count': 'أسئلة',
    'exam.created_date': 'تم الإنشاء في',
    'exam.best_score': 'أفضل نتيجة',
    'exam.champion': 'البطل',
    'exam.questions_list': 'أسئلة الامتحان',
    'exam.no_questions': 'لا توجد أسئلة في هذا الامتحان.',
    'exam.tests_history': 'سجل الاختبارات',
    'exam.test_id': 'معرف الاختبار',
    'exam.candidate': 'المرشح',
    'exam.score': 'النتيجة',


    // Exam Form traductions
    'form.title': 'امتحان جديد',
    'form.edit_title': 'تعديل الامتحان',
    'form.subtitle': 'أنشئ امتحانك بأسئلة وأجوبة',
    'form.general_info': 'معلومات عامة',
    'form.description_placeholder': 'وصف الامتحان',
    'form.questions_section': 'الأسئلة',
    'form.question_content': 'محتوى السؤال',
    'form.question_placeholder': 'اكتب سؤالك هنا...',
    'form.question_description': 'الوصف (اختياري)',
    'form.question_desc_placeholder': 'تلميح أو شرح...',
    'form.answers_section': 'الإجابات',
    'form.answer_placeholder': 'محتوى الإجابة',
    'form.correct_answer': 'إجابة صحيحة',
    'form.wrong_answer': 'إجابة خاطئة',
    'form.save_question': 'حفظ السؤال',
    'form.update_question': 'تحديث السؤال',
    'form.remove_question': 'حذف السؤال',
    'form.remove_answer': 'حذف الإجابة',
    'form.update': 'تحديث الامتحان',
    'form.submit': 'إنشاء الامتحان',
    'form.loading': 'جاري التحميل...',
    'form.saving': 'جارٍ الحفظ...',
    'form.saved': 'تم الحفظ!',
    'form.error_state': 'خطأ',
    'form.back': 'رجوع',
    'form.cancel': 'إلغاء',
    'form.description': 'الوصف',
    'form.status': 'الحالة',
    'form.visibility': 'الرؤية',
    'form.public': 'عام',
    'form.private': 'خاص',
    'form.question': 'سؤال',
    'form.update_answer': 'تحديث الإجابة',
    'form.save_answer': 'حفظ الإجابة',
    'form.update_answer_short': 'تحديث',
    'form.no_questions': 'لا توجد أسئلة. انقر على الزر أدناه للبدء.',
    'form.add_answer': 'إضافة إجابة',
    'form.add_question': 'إضافة سؤال',

    'form.attachment': 'مستند أو فيديو داعم (اختياري)',
    'form.add_attachment': 'إرفاق ملف',
    'form.uploading': 'جارٍ الرفع...',
    'form.upload_error': 'خطأ أثناء رفع الملف.',
    'form.remove_attachment': 'إزالة الملف',
    'form.attachment_hint': 'PDF أو Word أو صورة أو صوت أو فيديو (بحد أقصى 50 ميغابايت)',

    'form.has_duration': 'تحديد مدة الاختبار',
    'form.duration_placeholder': 'المدة بالدقائق',
    'form.minutes': 'دقيقة',

    'test.half_time_warning': 'انقضى نصف الوقت',
    'test.end_warning': 'تنبيه، الوقت أوشك على الانتهاء!',
    'test.remaining': 'متبقية',
    'test.time_up_title': 'انتهى الوقت',
    'test.time_up_text': 'تم إرسال إجاباتك تلقائيًا.',

    'test.previous': 'السابق',
    'test.next': 'التالي',
    'form.previous_question': 'السابق',
    'form.next_question': 'التالي',

    'form.generate_ai': "إنشاء بالذكاء الاصطناعي",
    'form.ai_subject': "الموضوع",
    'form.ai_subject_placeholder': "مثال: المشتقات",
    'form.ai_subject_required': "الموضوع مطلوب.",
    'form.ai_level': "المستوى (اختياري)",
    'form.ai_level_placeholder': "مثال: البكالوريا",
    'form.ai_count': "عدد الأسئلة",
    'form.ai_language': "اللغة",
    'form.ai_multiple_correct': "السماح بعدة إجابات صحيحة لكل سؤال",
    'form.ai_generate_button': "إنشاء",
    'form.ai_generating': "جارٍ الإنشاء...",
    'form.ai_error': "حدث خطأ أثناء الإنشاء بالذكاء الاصطناعي.",

    'form.ai_difficulty': "مستوى الصعوبة",
    'form.ai_difficulty_easy': "سهل",
    'form.ai_difficulty_medium': "متوسط",
    'form.ai_difficulty_advanced': "متقدم",
    'form.ai_reference_file': "مستند مرجعي (اختياري)",
    'form.ai_add_reference_file': "إضافة مستند",
    'form.ai_reference_file_hint': "PDF أو Word (.docx) أو نص (.txt) — 10 ميغابايت كحد أقصى",
    'form.ai_file_too_large': "الملف يتجاوز 10 ميغابايت.",
    // Status
    'status.CREATED': 'تم الإنشاء',
    'status.ACTIVATED': 'مفعّل',
    'status.SUSPENDED': 'موقوف',

    // Math Editor
    'math_editor.show_symbols': 'إظهار الرموز',
    'math_editor.hide_symbols': 'إخفاء الرموز',
    'math_editor.show_preview': 'إظهار المعاينة',
    'math_editor.hide_preview': 'إخفاء المعاينة',
    'math_editor.add_description': 'إضافة وصف',
    'math_editor.hide_description': 'إخفاء الوصف',

    // Users
    'users.title': 'المستخدمون',
    'users.add': '+ إضافة',
    'users.new_title': 'مستخدم جديد',
    'users.edit_title': 'تعديل المستخدم',
    'users.name': 'الاسم',
    'users.email': 'البريد الإلكتروني',
    'users.password': 'كلمة المرور',
    'users.name_ph': 'الاسم الكامل',
    'users.email_ph': 'email@example.com',
    'users.pass_ph': '••••••••',
    'users.cancel': 'إلغاء',
    'users.create': 'إنشاء',
    'users.update': 'تحديث',
    'users.loading': 'جارٍ التحميل...',
    'users.delete_confirm': 'حذف هذا المستخدم؟',

    // Groups
    'groups.title': 'مجموعاتي',
    'groups.subtitle': 'إدارة مجموعاتك ومشاركة الامتحانات',
    'groups.create': 'إنشاء مجموعة',
    'groups.create_new': 'إنشاء مجموعة جديدة',
    'groups.name': 'اسم المجموعة',
    'groups.description': 'الوصف',
    'groups.no_description': 'لا يوجد وصف',
    'groups.loading': 'جاري تحميل المجموعات...',
    'groups.empty': 'ليس لديك أي مجموعة بعد',
    'groups.create_first': 'إنشاء مجموعتي الأولى',
    'groups.add_member': 'إضافة عضو',
    'groups.add_exam': 'إضافة امتحان',
    'groups.members': 'الأعضاء',
    'groups.admins': 'المشرفون',
    'groups.delete_confirm': 'حذف هذه المجموعة؟',
    'groups.remove_member_confirm': 'إزالة هذا العضو؟',
    'groups.cancel': 'إلغاء',
    'groups.search_user': 'البحث عن مستخدم',
    'groups.select_exam': 'اختيار امتحان',
    'groups.choose_exam': 'اختر امتحاناً',
    'groups.share': 'مشاركة',
    'groups.add': 'إضافة',
    'groups.join_requests': 'طلبات الانضمام',
    'groups.no_requests': 'لا توجد طلبات معلقة',
    'groups.shared_exams': 'الامتحانات المشتركة',
    'groups.view_exam': 'عرض الامتحان',
    'groups.remove_exam': 'إزالة من المجموعة',
    'groups.confirm_remove_exam': 'هل تريد إزالة هذا الامتحان من المجموعة؟',
    'groups.error_remove_exam': 'خطأ أثناء إزالة الامتحان',
    'groups.by': 'بواسطة',
    'groups.creator': 'تم الإنشاء بواسطة',
    'groups.accept': 'قبول',
    'groups.reject': 'رفض',
    'groups.admin_badge': 'مشرف',
    'groups.more_members': 'آخرين',
    'groups.remove_member': 'إزالة العضو',
    'groups.delete_group': 'حذف المجموعة',
    'groups.requests_title': 'طلبات الانضمام',
    'groups.name_placeholder': 'اسم المجموعة',
    'groups.desc_placeholder': 'وصف المجموعة',
    'groups.search_placeholder': 'البحث بالاسم أو البريد...',
    'groups.unknown_creator': 'منشئ غير معروف',
    'groups.no_group_selected': 'لم يتم اختيار مجموعة',


    'groups.requests_disabled_title': 'يمكن للمشرفين فقط رؤية الطلبات',


    'groups.confirm_remove_exam_title': 'إزالة الامتحان',
    'groups.confirm_remove_exam_text': 'هل تريد بالتأكيد إزالة هذا الامتحان من المجموعة؟',
    'groups.confirm_remove_exam_confirm': 'نعم، إزالة',
    'groups.confirm_remove_exam_cancel': 'إلغاء',
    'groups.exam_removed_success': 'تمت إزالة الامتحان بنجاح!',
    'groups.exam_removed_error': 'لا يمكن إزالة الامتحان من المجموعة.',
    'groups.exam_removed_toast': 'تم إزالة الامتحان',

    'groups.confirm_share_exam_title': 'مشاركة امتحان',
    'groups.confirm_share_exam_text': 'هل تريد بالتأكيد مشاركة هذا الامتحان مع هذه المجموعة؟',
    'groups.confirm_share_exam_confirm': 'نعم، مشاركة',
    'groups.confirm_share_exam_cancel': 'إلغاء',
    'groups.exam_shared_success': 'تمت مشاركة الامتحان بنجاح!',
    'groups.exam_shared_error': 'لا يمكن مشاركة الامتحان مع المجموعة.',
    'groups.exam_shared_toast': 'تمت مشاركة الامتحان',

    'groups.confirm_delete_group_title': 'حذف المجموعة',
    'groups.confirm_delete_group_text': 'هل تريد بالتأكيد حذف هذه المجموعة؟ هذا الإجراء لا رجعة فيه.',
    'groups.confirm_delete_group_confirm': 'نعم، حذف',
    'groups.confirm_delete_group_cancel': 'إلغاء',
    'groups.group_deleted_success': 'تم حذف المجموعة بنجاح!',
    'groups.group_deleted_error': 'لا يمكن حذف المجموعة.',

    'groups.confirm_join_request_title': 'طلب الانضمام',
    'groups.confirm_join_request_text': 'هل تريد بالتأكيد طلب الانضمام إلى هذه المجموعة؟',
    'groups.confirm_join_request_confirm': 'نعم، إرسال الطلب',
    'groups.confirm_join_request_cancel': 'إلغاء',
    'groups.join_request_sent': 'تم إرسال الطلب بنجاح!',
    'groups.join_request_pending': 'طلب معلق بالفعل',
    'groups.join_request_error': 'خطأ في إرسال الطلب',
    'groups.already_member': 'أنت بالفعل عضو في هذه المجموعة',

    'groups.add_member_tooltip': 'إضافة عضو إلى المجموعة',
    'groups.add_exam_tooltip': 'مشاركة امتحان مع المجموعة',
    'groups.add_member_disabled_tooltip': 'يمكن للمشرفين فقط إضافة أعضاء',
    'groups.add_exam_disabled_tooltip': 'يمكن للمشرفين فقط مشاركة الامتحانات',

    'groups.remove_exam_disabled_tooltip': 'يمكن للمشرفين فقط إزالة الامتحانات',

    'groups.already_member_of_group': 'هو بالفعل عضو في هذه المجموعة.',
    'groups.member_added': 'انضم إلى المجموعة',
    'groups.add_member_error': 'لا يمكن إضافة العضو.',

    'groups.exam_already_shared': 'الامتحان تمت مشاركته بالفعل',
    'groups.exam_already_shared_text': 'هذا الامتحان تمت مشاركته بالفعل مع هذه المجموعة:',

    // Correction
    'correction.loading': 'جاري تحميل التصحيح...',
    'correction.congrats': 'مبروك! نتيجة ممتازة!',
    'correction.keep_trying': 'واصل جهودك!',
    'correction.summary': 'ملخص',
    'correction.correct': 'إجابات صحيحة',
    'correction.incorrect': 'إجابات خاطئة',
    'correction.detailed': 'تصحيح مفصل',
    'correction.your_answer': 'إجابتك',
    'correction.correct_answer': 'الإجابة الصحيحة',
    'correction.explanation': 'شرح',
    'correction.no_answer': 'لا توجد إجابة',
    'correction.back_to_dashboard': 'العودة إلى لوحة التحكم',
    'correction.detailed_title': '📝 التصحيح المفصل',
    'correction.question_label': 'سؤال',
    'correction.correct_badge': '✓ صحيح',
    'correction.incorrect_badge': '✗ خاطئ',
    'correction.your_answer_correct_text': '✓ لقد اخترت (إجابة صحيحة)',
    'correction.your_answer_wrong_text': '✗ لقد اخترت (إجابة خاطئة)',
    'correction.correct_not_selected_text': '💡 الإجابة الصحيحة غير محددة',
    'correction.not_selected_text': '• غير محدد',
    'correction.hint_text': '💡 الإجابة الصحيحة هي:',

    'test.confirm_title': 'بدء الاختبار',
    'test.confirm_text': 'هل أنت مستعد لاجتياز الإختبار رقم :',
    'test.confirm_confirm': '🎯 بدء',
    'test.confirm_cancel': 'إلغاء',

    'test.created_by': 'تم الإنشاء بواسطة',
    'test.questions_count': 'الأسئلة',
    'test.progress': 'التقدم',
    'test.question': 'سؤال',
    'test.answers_selected': 'إجابة(إجابات) محددة',
    'test.warning': 'لقد أجبت على',
    'test.on': 'من',
    'test.submit': 'إرسال الاختبار',
    'test.submitting': 'جاري الإرسال...',
    'test.loading': 'جاري تحميل الاختبار...',

    'test.incomplete_title': 'الاختبار غير مكتمل',
    'test.incomplete_text': 'الرجاء الإجابة على جميع الأسئلة قبل الإرسال.',
    'test.continue': 'متابعة',
    'test.confirm_submit_title': 'إرسال الاختبار',
    'test.confirm_submit_text': 'هل تريد بالتأكيد إرسال إجاباتك ل',
    'test.confirm_submit_confirm': 'نعم، إرسال',
    'test.confirm_submit_cancel': 'لا، التحقق مرة أخرى',
    'test.success': 'تم إرسال الاختبار!',
    'test.success_message': 'تم تسجيل إجاباتك بنجاح.',
    'test.error': 'خطأ',
    'test.error_message': 'حدث خطأ أثناء الإرسال.',
    'test.close': 'إغلاق',

    //test-result
    'test_result.loading': 'جاري تحميل النتائج...',
    'test_result.back_to_dashboard': 'العودة إلى لوحة التحكم',
    'test_result.congrats': '🎉 مبروك!',
    'test_result.keep_trying': '📚 واصل جهودك!',
    'test_result.summary': 'ملخص الاختبار',
    'test_result.candidate_name': 'اسم المرشح',
    'test_result.exam_creator': 'منشئ الامتحان',
    'test_result.correct_answers': 'الإجابات الصحيحة',
    'test_result.wrong_answers': 'الإجابات الخاطئة',
    'test_result.score': 'الدرجة المحصلة',
    'test_result.date': 'تاريخ الاختبار',
    'test_result.view_correction': 'عرض التصحيح المفصل',

    'exams.tests': 'الاختبارات',
    'exams.tests_list': 'الاختبارات المجتازة',
    'exams.candidate': 'المرشح',
    'exams.score': 'الدرجة',
    'exams.percentage': 'النسبة المئوية',
    'exams.no_tests': 'لا توجد اختبارات',
    'exams.no_tests_text': 'لم يتم اجتياز هذا الامتحان بعد.',
    'exams.close': 'إغلاق',

    'exams.access_denied': 'وصول مرفوض',
    'exams.no_rights': 'ليس لديك الحق في الاطلاع على نتائج هذا الامتحان.',

    'test_result.retake_test': ' إعادة الاختبار',
    'test_result.retake_confirm_title': 'محاولة جديدة',
    'test_result.retake_confirm_text': 'هل تريد بالتأكيد إعادة هذا الاختبار؟',
    'test_result.retake_confirm_yes': 'نعم، إعادة',
    'test_result.retake_confirm_no': 'لا، إلغاء',

    ///
    'test.limit_reached_title': 'تم الوصول إلى الحد الأقصى',
    'test.limit_reached_text': 'لقد استخدمت محاولاتك الثلاث لهذا الامتحان.',
    'test.limit_reached': 'تم الوصول إلى الحد الأقصى من المحاولات.',


    'exams.test_details': 'تفاصيل الاختبار',
    'exams.correct_answers': 'الإجابات الصحيحة',
    'exams.wrong_answers': 'الإجابات الخاطئة',
    'exams.test_id': 'معرف الاختبار',

    'exams.view_details': 'عرض التفاصيل',



    // Result
    'result.view_correction': 'عرض التصحيح',
    'result.back_to_dashboard': 'العودة إلى لوحة التحكم',

    'groups.make_public': 'جعل هذه المجموعة عامة',
    'groups.public_hint': 'المجموعات العامة مرئية للجميع ويمكن الانضمام إليها مباشرة.',

    //Admin
    'admin.title': "الإدارة",
    'admin.subtitle': "إدارة المنصة",
    'admin.tab_stats': "الإحصائيات",
    'admin.tab_users': "المستخدمون",
    'admin.tab_exams': "الامتحانات",
    'admin.tab_groups': "المجموعات",
    'admin.loading': "جارٍ التحميل...",
    'admin.stat_users': "المستخدمون",
    'admin.stat_exams': "الامتحانات",
    'admin.stat_questions': "الأسئلة",
    'admin.stat_groups': "المجموعات",
    'admin.stat_tests': "الاختبارات المنجزة",
    'admin.search_user': "البحث عن مستخدم...",
    'admin.search_exam': "البحث عن امتحان...",
    'admin.search_group': "البحث عن مجموعة...",
    'admin.col_name': "الاسم",
    'admin.col_email': "البريد الإلكتروني",
    'admin.col_code': "الرمز",
    'admin.col_description': "الوصف",
    'admin.col_visibility': "الظهور",
    'admin.col_actions': "الإجراءات",
    'admin.col_group_name': "اسم المجموعة",
    'admin.col_creator': "المنشئ",
    'admin.col_members': "الأعضاء",
    'admin.promote': "ترقية",
    'admin.demote': "تخفيض",
    'admin.delete_user': "حذف المستخدم",
    'admin.delete_exam': "حذف الامتحان",
    'admin.delete_group': "حذف المجموعة",
    'admin.confirm_promote': "ترقية هذا المستخدم إلى مسؤول؟",
    'admin.confirm_demote': "إزالة صلاحيات المسؤول؟",
    'admin.confirm_delete_user': "حذف هذا المستخدم؟",
    'admin.confirm_delete_exam': "حذف هذا الامتحان؟",
    'admin.confirm_delete_group': "حذف هذه المجموعة؟",
    'admin.confirm_yes': "نعم",
    'admin.confirm_no': "إلغاء",
    'admin.promoted_success': "تمت ترقية المستخدم",
    'admin.demoted_success': "تمت إزالة صلاحيات المسؤول",
    'admin.deleted_user_success': "تم حذف المستخدم",
    'admin.deleted_exam_success': "تم حذف الامتحان",
    'admin.deleted_group_success': "تم حذف المجموعة",
    'admin.action_error': "حدث خطأ.",
    'admin.cannot_delete_self': "لا يمكنك حذف حسابك الخاص هنا.",
    'nav.admin': "الإدارة",
  }
};

@Injectable({ providedIn: 'root' })
export class LangService {
  lang = signal<Lang>(
      (localStorage.getItem('lang') as Lang) ?? 'fr'
  );

  /** Cycle entre les 3 langues dans l'ordre fr → en → ar → fr... */
  toggle() {
    const order: Lang[] = ['fr', 'en', 'ar'];
    const currentIndex = order.indexOf(this.lang());
    const next = order[(currentIndex + 1) % order.length];
    this.lang.set(next);
    localStorage.setItem('lang', next);
    document.documentElement.dir = next === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = next;
  }

  t(key: string): string {
    return TRANSLATIONS[this.lang()][key] ?? key;
  }

  get isRtl(): boolean {
    return this.lang() === 'ar';
  }
}